Repository epershinaass/exchange_typescript, pull requests merged in 2022-07, with the labels that each got.

#2 feat: added docker-compose for local development
  .Dockerignore
  Dockerfile
  datasource.yaml
  docker-compose.yaml
  loki-config.yaml
  promtail-config.yaml
Labels: enhancement

#9 feat: add kafka schema registry & kafka connector
  Dockerfile-MongoConnect
  docker-compose.yaml
Labels: enhancement

#13 feat: add kafka ram and cpu reduce
  docker-compose.yaml
Labels: enhancement

#18 perf: add profiles
  docker-compose.yaml
Labels: team review

#12 feat: add IaC to project
  infra/ansible/.ansible-lint
  infra/ansible/ansible.cfg
  infra/ansible/files/deploy.pub
  infra/ansible/files/jo.pub
  infra/ansible/files/nikita.pub
  infra/ansible/inventory/group_vars/all/list_users.yml
  infra/ansible/inventory/group_vars/all/users.yml
  infra/ansible/inventory/hosts
  infra/ansible/main.yml
  infra/ansible/roles/ansible-role-users/LICENSE
  infra/ansible/roles/ansible-role-users/README.md
  infra/ansible/roles/ansible-role-users/defaults/main.yml
  infra/ansible/roles/ansible-role-users/meta/main.yml
  infra/ansible/roles/ansible-role-users/tasks/distribution-CentOS.yml
  infra/ansible/roles/ansible-role-users/tasks/distribution-Debian.yml
  infra/ansible/roles/ansible-role-users/tasks/distribution-RedHat.yml
  infra/ansible/roles/ansible-role-users/tasks/distribution-Ubuntu.yml
  infra/ansible/roles/ansible-role-users/tasks/distribution-default.yml
  infra/ansible/roles/ansible-role-users/tasks/main.yml
  infra/ansible/roles/ansible-role-users/tasks/setup-Buildroot.yml
  infra/ansible/roles/ansible-role-users/tasks/setup-Debian.yml
  infra/ansible/roles/ansible-role-users/tasks/setup-RedHat.yml
  infra/ansible/roles/ansible-role-users/templates/etc/sudoers.d/00-admin
  infra/ansible/roles/ansible-role-users/vars/main.yml
  infra/ansible/roles/haxorof.docker_ce/.ansible-lint
  infra/ansible/roles/haxorof.docker_ce/.editorconfig
  infra/ansible/roles/haxorof.docker_ce/.gitattributes
  infra/ansible/roles/haxorof.docker_ce/.gitignore
  infra/ansible/roles/haxorof.docker_ce/CHANGELOG.md
  infra/ansible/roles/haxorof.docker_ce/DOCKER_CE_MATRIX.md
  infra/ansible/roles/haxorof.docker_ce/LICENSE
  infra/ansible/roles/haxorof.docker_ce/README.md
  infra/ansible/roles/haxorof.docker_ce/defaults/main.yml
  infra/ansible/roles/haxorof.docker_ce/files/etc/audit/rules.d/docker.rules
  infra/ansible/roles/haxorof.docker_ce/handlers/main.yml
  infra/ansible/roles/haxorof.docker_ce/meta/.galaxy_install_info
  infra/ansible/roles/haxorof.docker_ce/meta/main.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/bug-tweaks.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/bug-tweaks/bug-centos7-resource-busy.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/bug-tweaks/lvm-thinpool.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/bug-tweaks/tweak-debian8-directlvm.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/checks.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/checks/compatibility-checks.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/checks/distribution-checks.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/configure-docker.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/configure-docker/configure-docker-plugins.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/configure-docker/configure-non-systemd.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/configure-docker/configure-systemd.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/install-docker.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/main.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/postinstall.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/remove-docker.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/remove-pre-docker-ce.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/setup-audit.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/setup-repository-Debian.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/setup-repository-RedHat.yml
  infra/ansible/roles/haxorof.docker_ce/tasks/setup-repository.yml
  infra/ansible/roles/haxorof.docker_ce/templates/docker-envs.j2
  infra/ansible/roles/haxorof.docker_ce/templates/drop-ins/default.conf.j2
  infra/ansible/roles/haxorof.docker_ce/vars/main.yml
Labels: enhancement

#21 feat: add monitoring system
  docker-compose.yaml
Labels: enhancement, team review

#27 feat: Add database initialization script
  .gitignore
  docker-compose.yaml
  infra/mongodb/mongo-init.sh
Labels: enhancement

#26 ci: add dockerfile validation
  .github/workflows/docker-lint.yml
Labels: team review

#25 perf: update versions & update dockerfile
  Dockerfile
  docker-compose.yaml
Labels: team review

#22 Accout refill facade and method
  .gitignore
  balance/.dockerignore
  balance/.env
  balance/.eslintrc.js
  balance/.prettierrc
  balance/Dockerfile
  balance/README.md
  balance/nest-cli.json
  balance/package.json
  balance/src/balance.controller.ts
  balance/src/balance.module.ts
  balance/src/balance.service.ts
  balance/src/dto/get-balance.dto.ts
  balance/src/dto/refill-balance.dto.ts
  balance/src/errors/balance.error.ts
  balance/src/interfaces/balance.interface.ts
  balance/src/main.ts
  balance/src/proto/balance.proto
  balance/src/schemas/balance.schema.ts
  balance/test/app.e2e-spec.ts
  balance/test/jest-e2e.json
  balance/tsconfig.build.json
  balance/tsconfig.json
  balance/yarn.lock
  docker-compose.yaml
  facade/.dockerignore
  facade/.eslintrc.js
  facade/.prettierrc
  facade/Dockerfile
  facade/README.md
  facade/nest-cli.json
  facade/package.json
  facade/src/app.module.ts
  facade/src/balance/balance.controller.ts
  facade/src/balance/dto/get-balance.dto.ts
  facade/src/balance/dto/refill-balance.dto.ts
  facade/src/balance/interfaces/grpc.interface.ts
  facade/src/balance/proto/balance.proto
  facade/src/main.ts
  facade/src/proto/facade.proto
  facade/test/app.e2e-spec.ts
  facade/test/jest-e2e.json
  facade/tsconfig.build.json
  facade/tsconfig.json
  facade/yarn.lock
Labels: team review

#38 ci: add build facade
  .github/workflows/build-facade.yml
Labels: team review

#40 ci: remove tag
  .github/workflows/build-facade.yml
Labels: team review

#30 ci: send telegram message on push
  .github/workflows/telegram.yml
Labels: team review

#39 ci: update variables
  .github/workflows/docker-compose-remote.yaml
Labels: team review

#31 feat: add remote deploy
  .github/workflows/docker-compose-remote.yaml
  infra/ansible/inventory/hosts
Labels: team review

#42 ci: add exports
  .github/workflows/docker-compose-remote.yaml
Labels: team review

#45 fix: prometheus target unauthorized
  infra/prometheus.yml
  infra/web.yml
Labels: team review

#44 fix: update alertmanager config
  infra/alertmanager-config.yml
Labels: team review

#46 fix: fix basic auth
  infra/prometheus.yml
Labels: team review

#53 refactor: change scrape configs
  infra/promtail-config.yaml
Labels: team review

#51 ci: add validator filters
  .github/workflows/docker-lint.yml
Labels: team review

#52 style: change names
  .github/workflows/build-facade.yml
  .github/workflows/telegram.yml
Labels: team review

#29 ci: add build balance
  .github/workflows/build-balance.yml
  Dockerfile
Labels: team review

#57 feat: add scrape for promtail
  infra/promtail-config.yaml
Labels: team review

#62 fix: change dockerfile path
  .github/workflows/build-balance.yml
Labels: team review

#61 perf: update dashboards
  infra/dashboards/docker_containers.json
  infra/dashboards/docker_host.json
Labels: team review

#63 fix: Kafka restarting
  infra/docker-compose.yaml
Labels: team review

#64 feat: add actions timeout
  .github/workflows/build-balance.yml
  .github/workflows/build-facade.yml
  .github/workflows/docker-compose-remote.yaml
  .github/workflows/docker-lint.yml
  .github/workflows/telegram.yml
Labels: team review

#65 fix: close prometheus port
  infra/docker-compose.yaml
Labels: team review

#66 perf: add profiles for services
  docker-compose.yaml
Labels: team review

#67 perf: add userns mode
  infra/docker-compose.yaml
Labels: team review

#69 perf: add zoo 4lw command whitelist
  infra/docker-compose.yaml
Labels: team review

#70 feat: add cadvisor volume
  infra/docker-compose.yaml
Labels: team review

#74 ci: docker login
  .github/workflows/docker-compose-remote.yaml
Labels: team review

#75 feat: add mongodb dashboard
  infra/docker-compose.yaml
Labels: team review

#79 feat: use kafka kraft
  docker-compose.yaml
  infra/update_run.sh
Labels: team review
