Repository epershinaass/exchange_typescript, pull requests merged in 2022-08, with the labels that each got.

#80 perf: update local kafka & local deploy
  Dockerfile
  docker-compose.yaml
  infra/datasource.yaml
Labels: team review

#85 doc: update readme
  README.md
  docker-compose.yaml
Labels: team review

#86 feat: add mongo cluster
  .github/workflows/docker-compose-remote.yaml
  .gitignore
  infra/.dockerignore
  infra/docker-compose.yaml
  infra/mongodb/mongosetup.sh
  infra/prometheus.yml
Labels: team review

#89 Mongodb init
  README.md
  balance/.dockerignore
  facade/.dockerignore
Labels: team review

#84 feat: add loki simple scalable mode
  .github/workflows/docker-compose-remote.yaml
  infra/datasource-auth.yaml
  infra/docker-compose.yaml
  infra/haproxy.cfg
  infra/loki-config-scalable.yaml
  infra/prometheus.yml
  infra/promtail-config-scalable.yaml
Labels: team review

#81 ci: update dockerlint workflow
  .github/workflows/docker-lint.yml
Labels: team review

#82 feat: add kafka cluster
  .github/workflows/docker-compose-remote.yaml
  .gitignore
  docker-compose.yaml
  infra/.dockerignore
  infra/alert.rules
  infra/docker-compose.yaml
  infra/jmx-exporter-config.yml
  infra/jmx-sr-exporter-config.yml
  infra/prometheus.yml
  infra/update_run_cluster.sh
Labels: team review

#90 ci: fix refers to undefined config
  infra/docker-compose.yaml
Labels: team review

#35 feat: products service
  facade/src/app.module.ts
  facade/src/products/dto/add-products.dto.ts
  facade/src/products/interfaces/grpc.interface.ts
  facade/src/products/products.controller.ts
  facade/src/products/proto/products.proto
  facade/src/proto/facade.proto
  products/.dockerignore
  products/.env
  products/.eslintrc.js
  products/.gitignore
  products/.prettierrc
  products/README.md
  products/nest-cli.json
  products/package.json
  products/src/app.controller.spec.ts
  products/src/dto/create-product.dto.ts
  products/src/errors/products.error.ts
  products/src/interfaces/object.interface.ts
  products/src/main.ts
  products/src/products.controller.ts
  products/src/products.module.ts
  products/src/products.proto
  products/src/products.service.ts
  products/src/schemas/product.schema.ts
  products/test/app.e2e-spec.ts
  products/test/jest-e2e.json
  products/tsconfig.build.json
  products/tsconfig.json
  products/yarn.lock
  yarn.lock
Labels: merge

#100 perf: add grafana dashboards
  infra/alert.rules
  infra/dashboards/JMX-kafka.json
  infra/dashboards/JMX-schema-registry.json
  infra/dashboards/Kafka-Metrics.json
  infra/dashboards/Mongodb-owerview.json
  infra/dashboards/Mongodb.json
  infra/dashboards/kafka-exporter-overview_rev5.json
  infra/dashboards/minio-dashboards.json
Labels: team review

#93 perf: create containers
  README.md
  docker-compose.yaml
  facade/Dockerfile
  facade/Dockerfile-dev
  facade/package.json
  products/.dockerignore
  products/.gitignore
  products/example.env
  products/package.json
Labels: team review

#102 perf: update Prometheus alerts
  infra/alert.rules
Labels: team review

#101 ci: add Dockerfile lint
  .github/workflows/docker-lint.yml
Labels: team review

#99 ci: update deploy
  .github/workflows/docker-compose-remote.yaml
  infra/docker-compose.yaml
Labels: team review

#54 Update Balance microservice, mongo update is atomic now
  balance/src/balance.controller.ts
  balance/src/balance.service.ts
  balance/src/errors/balance.error.ts
  balance/src/interfaces/balance.interface.ts
  balance/src/main.ts
  balance/src/proto/balance.proto
  balance/src/schemas/balance.schema.ts
  docker-compose.yaml
  facade/src/balance/balance.controller.ts
  facade/src/balance/interfaces/grpc.interface.ts
  facade/src/balance/proto/balance.proto
  facade/src/proto/facade.proto
  facade/yarn.lock
Labels: merge

#107 feat: add dev services
  README.md
  docker-compose.yaml
Labels: team review

#106 feat: add loki rule
  infra/alertmanager-config.yml
  infra/docker-compose.yaml
  infra/loki-rules.yml
Labels: team review

#111 Adr draft for order service
  doc/0004-adr-order.md
  doc/img/order-balance-kafka.png
  doc/img/order-products-kafka.png
  doc/img/order-scheme.png
Labels: documentation, merge

#48 Auth service
  README.md
  account/.dockerignore
  account/.eslintrc.js
  account/.prettierrc
  account/README.md
  account/example.env
  account/nest-cli.json
  account/package.json
  account/src/account-controller.ts
  account/src/account.module.ts
  account/src/account.service.ts
  account/src/dto/account.dto.ts
  account/src/errors/account.error.ts
  account/src/interfaces/account.interface.ts
  account/src/main.ts
  account/src/proto/account.proto
  account/src/schemas/account.schema.ts
  account/test/app.e2e-spec.ts
  account/test/jest-e2e.json
  account/tsconfig.build.json
  account/tsconfig.json
  account/yarn.lock
  doc/adr/0001-record-architecture-decisions.md
  doc/adr/0002-auth-users-adr.md
  docker-compose.yaml
  facade/example.env
  facade/src/account/account.controller.ts
  facade/src/account/account.module.ts
  facade/src/account/constants.ts
  facade/src/account/dto/account-dto.ts
  facade/src/account/interface/account-grpc-interface.ts
  facade/src/account/proto/account.proto
  facade/src/app.module.ts
  facade/src/balance/balance.controller.ts
  facade/src/balance/balance.module.ts
  facade/src/balance/constatns/constants.ts
  facade/src/filter/grpc-exception-filter.ts
  facade/src/main.ts
  facade/src/products/constants.ts
  facade/src/products/products.controller.ts
  facade/src/products/products.module.ts
  facade/src/proto/facade.proto
Labels: enhancement, merge

#125 feat: add second collection and checkout for products
  facade/package.json
  facade/src/products/interfaces/grpc.interface.ts
  facade/src/products/products.module.ts
  facade/src/products/proto/products.proto
  facade/src/proto/facade.proto
  products/.dockerignore
  products/src/interfaces/products.interfaces.ts
  products/src/products.controller.ts
  products/src/products.module.ts
  products/src/products.service.ts
  products/src/proto/products.proto
  products/src/schemas/product.schema.ts
  products/src/schemas/productsCollection.schema.ts
  yarn.lock
Labels: team review

#120 feat: add createId
  balance/src/balance.module.ts
  docker-compose.yaml
  facade/src/app.module.ts
  facade/src/common/create-id/create-id.ts
  facade/src/common/create-id/createId.controller.ts
  facade/src/common/create-id/dto/create-id.dto.ts
  facade/src/common/create-id/proto/createId.proto
  facade/src/proto/facade.proto
Labels: team review

#153 fix: add new field
  balance/src/schemas/balance.schema.ts
Labels: team review

#168 facade for order
  facade/example.env
  facade/src/app.module.ts
  facade/src/order/constatns/constants.ts
  facade/src/order/dto/order.dto.ts
  facade/src/order/interfaces/grpc.interface.ts
  facade/src/order/order.controller.ts
  facade/src/order/order.module.ts
  facade/src/order/proto/order.proto
  facade/src/proto/facade.proto
Labels: team review

#161 Passw hash
  .github/workflows/facade.yml
  account/example.env
  account/src/account-controller.ts
  account/src/account.module.ts
  account/src/account.service.ts
  account/src/dto/account.dto.ts
  account/src/errors/account.error.ts
  account/src/interfaces/account.interface.ts
  account/src/main.ts
  account/src/proto/account.proto
  account/src/schemas/account.schema.ts
  facade/example.env
  facade/package.json
  facade/src/account/account.controller.ts
  facade/src/account/account.module.ts
  facade/src/account/auth.guard.ts
  facade/src/account/auth.service.ts
  facade/src/account/constants.ts
  facade/src/account/dto/account-dto.ts
  facade/src/account/interface/account-grpc-interface.ts
  facade/src/account/jwt-auth.guard.ts
  facade/src/account/jwt.strategy.ts
  facade/src/account/proto/account.proto
  facade/src/account/public.ts
  facade/src/proto/facade.proto
  facade/yarn.lock
Labels: enhancement, invalid, team review
